version: "3.3"
services:
  virtuoso_db:
    image: openlink/virtuoso-opensource-7
    volumes:
      - ./data:/database/data
      - ./scripts:/opt/virtuoso-opensource/initdb.d
    environment:
      - DBA_PASSWORD=mysecret
      - VIRT_PARAMETERS_NUMBEROFBUFFERS=680000
      - VIRT_PARAMETERS_MAXDIRTYBUFFERS=500000
    ports:
      - "1111:1111"
      - "8890:8890"
